#!/bin/bash

# This script will be called by cron, to ensure that we'll keep the gpg keys in use through gpg-agent
# So when signing will come, keys will be available

logfile="/home/$USER/logs/cron-sign-test.log"

# Sourcing main functions
source ~/stylo-code/functions

for key in $(gpg --list-secret-keys|egrep -v secring|grep ^sec|awk '{print $2}'|cut -f 2 -d '/') ; do  
  candidate_file=$(mktemp)
  timeout 10 gpg --batch --sign -b --use-agent --local-user ${key}! ${candidate_file} >/dev/null 2>&1 
  if [ "$?" -ne "0" ] ; then     
    /bin/rm ${candidate_file}
    f_log "Not possible to sign with key ${key}"
    touch /home/$USER/logs/gpg.unready
    exit 1
  else     
    /bin/rm ${candidate_file} 
    f_log "Signing test with key ${key}: OK"
    test -e /home/$USER/logs/gpg.unready && rm /home/$USER/logs/gpg.unready 
  fi
done

